### ISSUE TITLE
Improve types to understand arrays of arrays

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cypress-each#2]
```js
it.each([
  [1, 'foo'],
  [2, 'bar']
])('title', (a, b) => {
  // a should be a number
  // b should be a string
})
```

**Comment by lastType** [comment]
Hello,
I'm sorry, i'm a noob trying to contribute, and in typescript.
Do you see my pull request for that pb ?

**Comment by DlgSHi** [comment]
@bahmutov Hi Gleb, is any chance to merge this fix? Or introduce `types`? Thanks in advance

**Comment by bahmutov** [comment]
I added an example spec showing the problem. The solution in https://github.com/lastType/cypress-each/pull/1/files solves type check in that example, but breaks every other spec :( if you run `npm run lint`.

**Comment by DlgSHi** [comment]
@bahmutov maybe it is because the simple typo ?
```
(this:Contexte,arg1:any,arg2:any)
```

instead of 
```
(this:Context,arg1:any,arg2:any)
```

`Context` without `e`

**Comment by DlgSHi** [comment]
I've tried to apply that change and:
just added new type.
```
type TestCallback4<T extends readonly any[]> = T extends []
    ? (this: Context, arg1: any, arg2: any) => void
    : Parameters<(...res: [...T, any, any]) => void> extends [...infer R]
    ? R extends readonly [...T, any, any]
      ? (this: Context, ...res: [...R]) => void
      : never
    : never
```
Applied all other changes suggested, and removed `cypress/**/*.js` file from type check (why the `*.js` file should be there?)  and it is working as expected :)

**Comment by bahmutov** [comment]
Mind opening a pr with the fix?Sent from my iPhoneOn Apr 25, 2023, at 08:53, Igor Dlugosh ***@***.***> wrote:﻿
I've tried to apply that change and:
just added new type.
type TestCallback4<T extends readonly any[]> = T extends []
    ? (this: Context, arg1: any, arg2: any) => void
    : Parameters<(...res: [...T, any, any]) => void> extends [...infer R]
    ? R extends readonly [...T, any, any]
      ? (this: Context, ...res: [...R]) => void
      : never
    : never

Applied all other changes suggested, and removed cypress/**/*.js file from type check (why the *.js file should be there?)  and it is working as expected :)

**Comment by DlgSHi** [comment]
Created https://github.com/bahmutov/cypress-each/pull/75

**Comment by bahmutov** [comment]
done
